//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANPHAT
    {
        public int ID { get; set; }
        public string LiDo { get; set; }
        public Nullable<decimal> PhiPhat { get; set; }
        public Nullable<int> IDThongTinMuonTra { get; set; }
    
        public virtual THONGTINMUONTRA THONGTINMUONTRA { get; set; }
    }
}
