//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPTAPHUAN
    {
        public LOPTAPHUAN()
        {
            this.NGUOIDANGKies = new HashSet<NGUOIDANGKY>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Phong { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
    
        public virtual ICollection<NGUOIDANGKY> NGUOIDANGKies { get; set; }
    }
}
