//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDANGKY
    {
        public int ID { get; set; }
        public string MSSV_MaHocVien { get; set; }
        public string Hoten { get; set; }
        public string Email { get; set; }
        public string Truong { get; set; }
        public Nullable<bool> XacNhan { get; set; }
        public Nullable<int> IDLopTapHuan { get; set; }
    
        public virtual LOPTAPHUAN LOPTAPHUAN { get; set; }
    }
}
