//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public PHONG()
        {
            this.LICHSUMUONPHONGs = new HashSet<LICHSUMUONPHONG>();
        }
    
        public int ID { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<LICHSUMUONPHONG> LICHSUMUONPHONGs { get; set; }
    }
}
