package entity;
// Generated Dec 10, 2014 9:29:01 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docgia generated by hbm2java
 */
@Entity
@Table(name="DOCGIA"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Docgia  implements java.io.Serializable {


     private int id;
     private String mhvMssv;
     private Serializable hoten;
     private Serializable diaChi;
     private String cmnd;
     private Serializable email;
     private Serializable truong;
     private Serializable khoa;
     private Serializable avatar;
     private Serializable loaiDocGia;
     private Set<Lichsumuonphong> lichsumuonphongs = new HashSet<Lichsumuonphong>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<Thongtinmuontra> thongtinmuontras = new HashSet<Thongtinmuontra>(0);

    public Docgia() {
    }

	
    public Docgia(int id) {
        this.id = id;
    }
    public Docgia(int id, String mhvMssv, Serializable hoten, Serializable diaChi, String cmnd, Serializable email, Serializable truong, Serializable khoa, Serializable avatar, Serializable loaiDocGia, Set<Lichsumuonphong> lichsumuonphongs, Set<User> users, Set<Thongtinmuontra> thongtinmuontras) {
       this.id = id;
       this.mhvMssv = mhvMssv;
       this.hoten = hoten;
       this.diaChi = diaChi;
       this.cmnd = cmnd;
       this.email = email;
       this.truong = truong;
       this.khoa = khoa;
       this.avatar = avatar;
       this.loaiDocGia = loaiDocGia;
       this.lichsumuonphongs = lichsumuonphongs;
       this.users = users;
       this.thongtinmuontras = thongtinmuontras;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="MHV_MSSV", length=10)
    public String getMhvMssv() {
        return this.mhvMssv;
    }
    
    public void setMhvMssv(String mhvMssv) {
        this.mhvMssv = mhvMssv;
    }

    
    @Column(name="Hoten")
    public Serializable getHoten() {
        return this.hoten;
    }
    
    public void setHoten(Serializable hoten) {
        this.hoten = hoten;
    }

    
    @Column(name="DiaChi")
    public Serializable getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(Serializable diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="CMND", length=10)
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }

    
    @Column(name="Email")
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }

    
    @Column(name="Truong")
    public Serializable getTruong() {
        return this.truong;
    }
    
    public void setTruong(Serializable truong) {
        this.truong = truong;
    }

    
    @Column(name="Khoa")
    public Serializable getKhoa() {
        return this.khoa;
    }
    
    public void setKhoa(Serializable khoa) {
        this.khoa = khoa;
    }

    
    @Column(name="Avatar")
    public Serializable getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(Serializable avatar) {
        this.avatar = avatar;
    }

    
    @Column(name="LoaiDocGia")
    public Serializable getLoaiDocGia() {
        return this.loaiDocGia;
    }
    
    public void setLoaiDocGia(Serializable loaiDocGia) {
        this.loaiDocGia = loaiDocGia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<Lichsumuonphong> getLichsumuonphongs() {
        return this.lichsumuonphongs;
    }
    
    public void setLichsumuonphongs(Set<Lichsumuonphong> lichsumuonphongs) {
        this.lichsumuonphongs = lichsumuonphongs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<Thongtinmuontra> getThongtinmuontras() {
        return this.thongtinmuontras;
    }
    
    public void setThongtinmuontras(Set<Thongtinmuontra> thongtinmuontras) {
        this.thongtinmuontras = thongtinmuontras;
    }




}


