package entity;
// Generated Dec 18, 2014 8:03:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lichsumuonphong generated by hbm2java
 */
@Entity
@Table(name="LICHSUMUONPHONG"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Lichsumuonphong  implements java.io.Serializable {


     private int id;
     private Docgia docgia;
     private Phong phong;
     private Date thoiGianMuon;
     private Date thoiGianTra;
     private Character deleteFlag;

    public Lichsumuonphong() {
    }

	
    public Lichsumuonphong(int id) {
        this.id = id;
    }
    public Lichsumuonphong(int id, Docgia docgia, Phong phong, Date thoiGianMuon, Date thoiGianTra, Character deleteFlag) {
       this.id = id;
       this.docgia = docgia;
       this.phong = phong;
       this.thoiGianMuon = thoiGianMuon;
       this.thoiGianTra = thoiGianTra;
       this.deleteFlag = deleteFlag;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDocGia")
    public Docgia getDocgia() {
        return this.docgia;
    }
    
    public void setDocgia(Docgia docgia) {
        this.docgia = docgia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPhong")
    public Phong getPhong() {
        return this.phong;
    }
    
    public void setPhong(Phong phong) {
        this.phong = phong;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ThoiGianMuon", length=23)
    public Date getThoiGianMuon() {
        return this.thoiGianMuon;
    }
    
    public void setThoiGianMuon(Date thoiGianMuon) {
        this.thoiGianMuon = thoiGianMuon;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ThoiGianTra", length=23)
    public Date getThoiGianTra() {
        return this.thoiGianTra;
    }
    
    public void setThoiGianTra(Date thoiGianTra) {
        this.thoiGianTra = thoiGianTra;
    }

    
    @Column(name="delete_flag", length=1)
    public Character getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(Character deleteFlag) {
        this.deleteFlag = deleteFlag;
    }




}


