package entity;
// Generated Dec 10, 2014 9:29:01 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LichsumuonphongId generated by hbm2java
 */
@Embeddable
public class LichsumuonphongId  implements java.io.Serializable {


     private int iddocGia;
     private int idphong;
     private Date thoiGianMuon;

    public LichsumuonphongId() {
    }

    public LichsumuonphongId(int iddocGia, int idphong, Date thoiGianMuon) {
       this.iddocGia = iddocGia;
       this.idphong = idphong;
       this.thoiGianMuon = thoiGianMuon;
    }
   


    @Column(name="IDDocGia", nullable=false)
    public int getIddocGia() {
        return this.iddocGia;
    }
    
    public void setIddocGia(int iddocGia) {
        this.iddocGia = iddocGia;
    }


    @Column(name="IDPhong", nullable=false)
    public int getIdphong() {
        return this.idphong;
    }
    
    public void setIdphong(int idphong) {
        this.idphong = idphong;
    }


    @Column(name="ThoiGianMuon", nullable=false, length=23)
    public Date getThoiGianMuon() {
        return this.thoiGianMuon;
    }
    
    public void setThoiGianMuon(Date thoiGianMuon) {
        this.thoiGianMuon = thoiGianMuon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LichsumuonphongId) ) return false;
		 LichsumuonphongId castOther = ( LichsumuonphongId ) other; 
         
		 return (this.getIddocGia()==castOther.getIddocGia())
 && (this.getIdphong()==castOther.getIdphong())
 && ( (this.getThoiGianMuon()==castOther.getThoiGianMuon()) || ( this.getThoiGianMuon()!=null && castOther.getThoiGianMuon()!=null && this.getThoiGianMuon().equals(castOther.getThoiGianMuon()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIddocGia();
         result = 37 * result + this.getIdphong();
         result = 37 * result + ( getThoiGianMuon() == null ? 0 : this.getThoiGianMuon().hashCode() );
         return result;
   }   


}


