package entity;
// Generated Dec 10, 2014 9:29:01 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lichsumuonphong generated by hbm2java
 */
@Entity
@Table(name="LICHSUMUONPHONG"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Lichsumuonphong  implements java.io.Serializable {


     private LichsumuonphongId id;
     private Docgia docgia;
     private Phong phong;
     private Date thoiGianTra;

    public Lichsumuonphong() {
    }

	
    public Lichsumuonphong(LichsumuonphongId id, Docgia docgia, Phong phong) {
        this.id = id;
        this.docgia = docgia;
        this.phong = phong;
    }
    public Lichsumuonphong(LichsumuonphongId id, Docgia docgia, Phong phong, Date thoiGianTra) {
       this.id = id;
       this.docgia = docgia;
       this.phong = phong;
       this.thoiGianTra = thoiGianTra;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iddocGia", column=@Column(name="IDDocGia", nullable=false) ), 
        @AttributeOverride(name="idphong", column=@Column(name="IDPhong", nullable=false) ), 
        @AttributeOverride(name="thoiGianMuon", column=@Column(name="ThoiGianMuon", nullable=false, length=23) ) } )
    public LichsumuonphongId getId() {
        return this.id;
    }
    
    public void setId(LichsumuonphongId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDocGia", nullable=false, insertable=false, updatable=false)
    public Docgia getDocgia() {
        return this.docgia;
    }
    
    public void setDocgia(Docgia docgia) {
        this.docgia = docgia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPhong", nullable=false, insertable=false, updatable=false)
    public Phong getPhong() {
        return this.phong;
    }
    
    public void setPhong(Phong phong) {
        this.phong = phong;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ThoiGianTra", length=23)
    public Date getThoiGianTra() {
        return this.thoiGianTra;
    }
    
    public void setThoiGianTra(Date thoiGianTra) {
        this.thoiGianTra = thoiGianTra;
    }




}


