package entity;
// Generated Dec 23, 2014 10:18:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Loptaphuan generated by hbm2java
 */
@Entity
@Table(name="LOPTAPHUAN"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Loptaphuan  implements java.io.Serializable {


     private int id;
     private Date ngay;
     private Serializable phong;
     private Date thoiGian;
     private Set<Nguoidangky> nguoidangkies = new HashSet<Nguoidangky>(0);

    public Loptaphuan() {
    }

	
    public Loptaphuan(int id) {
        this.id = id;
    }
    public Loptaphuan(int id, Date ngay, Serializable phong, Date thoiGian, Set<Nguoidangky> nguoidangkies) {
       this.id = id;
       this.ngay = ngay;
       this.phong = phong;
       this.thoiGian = thoiGian;
       this.nguoidangkies = nguoidangkies;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Ngay", length=10)
    public Date getNgay() {
        return this.ngay;
    }
    
    public void setNgay(Date ngay) {
        this.ngay = ngay;
    }

    
    @Column(name="Phong")
    public Serializable getPhong() {
        return this.phong;
    }
    
    public void setPhong(Serializable phong) {
        this.phong = phong;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ThoiGian", length=16)
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loptaphuan")
    public Set<Nguoidangky> getNguoidangkies() {
        return this.nguoidangkies;
    }
    
    public void setNguoidangkies(Set<Nguoidangky> nguoidangkies) {
        this.nguoidangkies = nguoidangkies;
    }




}


