package entity;
// Generated Dec 10, 2014 9:29:01 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name="NHANVIEN"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Nhanvien  implements java.io.Serializable {


     private int id;
     private Serializable tenNhanVien;
     private Serializable chucVu;
     private String email;
     private String sdt;
     private Set<Thongtinmuontra> thongtinmuontrasForIdnhanVienNhan = new HashSet<Thongtinmuontra>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<Thongtinmuontra> thongtinmuontrasForIdnhanVienTra = new HashSet<Thongtinmuontra>(0);

    public Nhanvien() {
    }

	
    public Nhanvien(int id) {
        this.id = id;
    }
    public Nhanvien(int id, Serializable tenNhanVien, Serializable chucVu, String email, String sdt, Set<Thongtinmuontra> thongtinmuontrasForIdnhanVienNhan, Set<User> users, Set<Thongtinmuontra> thongtinmuontrasForIdnhanVienTra) {
       this.id = id;
       this.tenNhanVien = tenNhanVien;
       this.chucVu = chucVu;
       this.email = email;
       this.sdt = sdt;
       this.thongtinmuontrasForIdnhanVienNhan = thongtinmuontrasForIdnhanVienNhan;
       this.users = users;
       this.thongtinmuontrasForIdnhanVienTra = thongtinmuontrasForIdnhanVienTra;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="TenNhanVien")
    public Serializable getTenNhanVien() {
        return this.tenNhanVien;
    }
    
    public void setTenNhanVien(Serializable tenNhanVien) {
        this.tenNhanVien = tenNhanVien;
    }

    
    @Column(name="ChucVu")
    public Serializable getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(Serializable chucVu) {
        this.chucVu = chucVu;
    }

    
    @Column(name="Email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="SDT", length=20)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanvienByIdnhanVienNhan")
    public Set<Thongtinmuontra> getThongtinmuontrasForIdnhanVienNhan() {
        return this.thongtinmuontrasForIdnhanVienNhan;
    }
    
    public void setThongtinmuontrasForIdnhanVienNhan(Set<Thongtinmuontra> thongtinmuontrasForIdnhanVienNhan) {
        this.thongtinmuontrasForIdnhanVienNhan = thongtinmuontrasForIdnhanVienNhan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docgia")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanvienByIdnhanVienTra")
    public Set<Thongtinmuontra> getThongtinmuontrasForIdnhanVienTra() {
        return this.thongtinmuontrasForIdnhanVienTra;
    }
    
    public void setThongtinmuontrasForIdnhanVienTra(Set<Thongtinmuontra> thongtinmuontrasForIdnhanVienTra) {
        this.thongtinmuontrasForIdnhanVienTra = thongtinmuontrasForIdnhanVienTra;
    }




}


