package entity;
// Generated Dec 18, 2014 8:03:55 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhaxuatban generated by hbm2java
 */
@Entity
@Table(name="NHAXUATBAN"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Nhaxuatban  implements java.io.Serializable {


     private int id;
     private Serializable tenNxb;
     private Serializable quocGia;
     private Set<Sach> saches = new HashSet<Sach>(0);

    public Nhaxuatban() {
    }

	
    public Nhaxuatban(int id) {
        this.id = id;
    }
    public Nhaxuatban(int id, Serializable tenNxb, Serializable quocGia, Set<Sach> saches) {
       this.id = id;
       this.tenNxb = tenNxb;
       this.quocGia = quocGia;
       this.saches = saches;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="TenNXB")
    public Serializable getTenNxb() {
        return this.tenNxb;
    }
    
    public void setTenNxb(Serializable tenNxb) {
        this.tenNxb = tenNxb;
    }

    
    @Column(name="QuocGia")
    public Serializable getQuocGia() {
        return this.quocGia;
    }
    
    public void setQuocGia(Serializable quocGia) {
        this.quocGia = quocGia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhaxuatban")
    public Set<Sach> getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set<Sach> saches) {
        this.saches = saches;
    }




}


