package entity;
// Generated Dec 18, 2014 8:03:55 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phong generated by hbm2java
 */
@Entity
@Table(name="PHONG"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Phong  implements java.io.Serializable {


     private int id;
     private Serializable trangThai;
     private Set<Lichsumuonphong> lichsumuonphongs = new HashSet<Lichsumuonphong>(0);

    public Phong() {
    }

	
    public Phong(int id) {
        this.id = id;
    }
    public Phong(int id, Serializable trangThai, Set<Lichsumuonphong> lichsumuonphongs) {
       this.id = id;
       this.trangThai = trangThai;
       this.lichsumuonphongs = lichsumuonphongs;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="TrangThai")
    public Serializable getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Serializable trangThai) {
        this.trangThai = trangThai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phong")
    public Set<Lichsumuonphong> getLichsumuonphongs() {
        return this.lichsumuonphongs;
    }
    
    public void setLichsumuonphongs(Set<Lichsumuonphong> lichsumuonphongs) {
        this.lichsumuonphongs = lichsumuonphongs;
    }




}


