package entity;
// Generated Dec 18, 2014 8:03:55 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name="SACH"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Sach  implements java.io.Serializable {


     private int id;
     private Chude chude;
     private Nhaxuatban nhaxuatban;
     private Nhomsach nhomsach;
     private Vitri vitri;
     private Serializable tenSach;
     private Date namXb;
     private Integer tap;
     private Integer cuon;
     private Serializable trangThai;
     private Serializable noiDungTomTat;
     private String mucLuc;
     private Set<Tacgia> tacgias = new HashSet<Tacgia>(0);
     private Set<Thongtinmuontra> thongtinmuontras = new HashSet<Thongtinmuontra>(0);

    public Sach() {
    }

	
    public Sach(int id) {
        this.id = id;
    }
    public Sach(int id, Chude chude, Nhaxuatban nhaxuatban, Nhomsach nhomsach, Vitri vitri, Serializable tenSach, Date namXb, Integer tap, Integer cuon, Serializable trangThai, Serializable noiDungTomTat, String mucLuc, Set<Tacgia> tacgias, Set<Thongtinmuontra> thongtinmuontras) {
       this.id = id;
       this.chude = chude;
       this.nhaxuatban = nhaxuatban;
       this.nhomsach = nhomsach;
       this.vitri = vitri;
       this.tenSach = tenSach;
       this.namXb = namXb;
       this.tap = tap;
       this.cuon = cuon;
       this.trangThai = trangThai;
       this.noiDungTomTat = noiDungTomTat;
       this.mucLuc = mucLuc;
       this.tacgias = tacgias;
       this.thongtinmuontras = thongtinmuontras;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDChuDe")
    public Chude getChude() {
        return this.chude;
    }
    
    public void setChude(Chude chude) {
        this.chude = chude;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNhaXuatBan")
    public Nhaxuatban getNhaxuatban() {
        return this.nhaxuatban;
    }
    
    public void setNhaxuatban(Nhaxuatban nhaxuatban) {
        this.nhaxuatban = nhaxuatban;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNhomSach")
    public Nhomsach getNhomsach() {
        return this.nhomsach;
    }
    
    public void setNhomsach(Nhomsach nhomsach) {
        this.nhomsach = nhomsach;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDViTri")
    public Vitri getVitri() {
        return this.vitri;
    }
    
    public void setVitri(Vitri vitri) {
        this.vitri = vitri;
    }

    
    @Column(name="TenSach")
    public Serializable getTenSach() {
        return this.tenSach;
    }
    
    public void setTenSach(Serializable tenSach) {
        this.tenSach = tenSach;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NamXB", length=10)
    public Date getNamXb() {
        return this.namXb;
    }
    
    public void setNamXb(Date namXb) {
        this.namXb = namXb;
    }

    
    @Column(name="Tap")
    public Integer getTap() {
        return this.tap;
    }
    
    public void setTap(Integer tap) {
        this.tap = tap;
    }

    
    @Column(name="Cuon")
    public Integer getCuon() {
        return this.cuon;
    }
    
    public void setCuon(Integer cuon) {
        this.cuon = cuon;
    }

    
    @Column(name="TrangThai")
    public Serializable getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Serializable trangThai) {
        this.trangThai = trangThai;
    }

    
    @Column(name="NoiDungTomTat")
    public Serializable getNoiDungTomTat() {
        return this.noiDungTomTat;
    }
    
    public void setNoiDungTomTat(Serializable noiDungTomTat) {
        this.noiDungTomTat = noiDungTomTat;
    }

    
    @Column(name="MucLuc", length=300)
    public String getMucLuc() {
        return this.mucLuc;
    }
    
    public void setMucLuc(String mucLuc) {
        this.mucLuc = mucLuc;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="TACGIA_SACH", schema="dbo", catalog="QuanLyThuVien", joinColumns = { 
        @JoinColumn(name="IDSach", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="IDTacGia", nullable=false, updatable=false) })
    public Set<Tacgia> getTacgias() {
        return this.tacgias;
    }
    
    public void setTacgias(Set<Tacgia> tacgias) {
        this.tacgias = tacgias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sach")
    public Set<Thongtinmuontra> getThongtinmuontras() {
        return this.thongtinmuontras;
    }
    
    public void setThongtinmuontras(Set<Thongtinmuontra> thongtinmuontras) {
        this.thongtinmuontras = thongtinmuontras;
    }




}


