package entity;
// Generated Dec 23, 2014 10:18:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thongtinmuontra generated by hbm2java
 */
@Entity
@Table(name="THONGTINMUONTRA"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Thongtinmuontra  implements java.io.Serializable {


     private int id;
     private Docgia docgia;
     private Nhanvien nhanvienByIdnhanVienNhan;
     private Nhanvien nhanvienByIdnhanVienTra;
     private Sach sach;
     private Date ngayMuon;
     private Date ngayTra;
     private Date hanTra;
     private Boolean giaHan;
     private Set<Banphat> banphats = new HashSet<Banphat>(0);

    public Thongtinmuontra() {
    }

	
    public Thongtinmuontra(int id) {
        this.id = id;
    }
    public Thongtinmuontra(int id, Docgia docgia, Nhanvien nhanvienByIdnhanVienNhan, Nhanvien nhanvienByIdnhanVienTra, Sach sach, Date ngayMuon, Date ngayTra, Date hanTra, Boolean giaHan, Set<Banphat> banphats) {
       this.id = id;
       this.docgia = docgia;
       this.nhanvienByIdnhanVienNhan = nhanvienByIdnhanVienNhan;
       this.nhanvienByIdnhanVienTra = nhanvienByIdnhanVienTra;
       this.sach = sach;
       this.ngayMuon = ngayMuon;
       this.ngayTra = ngayTra;
       this.hanTra = hanTra;
       this.giaHan = giaHan;
       this.banphats = banphats;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDocGia")
    public Docgia getDocgia() {
        return this.docgia;
    }
    
    public void setDocgia(Docgia docgia) {
        this.docgia = docgia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNhanVienNhan")
    public Nhanvien getNhanvienByIdnhanVienNhan() {
        return this.nhanvienByIdnhanVienNhan;
    }
    
    public void setNhanvienByIdnhanVienNhan(Nhanvien nhanvienByIdnhanVienNhan) {
        this.nhanvienByIdnhanVienNhan = nhanvienByIdnhanVienNhan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDNhanVienTra")
    public Nhanvien getNhanvienByIdnhanVienTra() {
        return this.nhanvienByIdnhanVienTra;
    }
    
    public void setNhanvienByIdnhanVienTra(Nhanvien nhanvienByIdnhanVienTra) {
        this.nhanvienByIdnhanVienTra = nhanvienByIdnhanVienTra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDSach")
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayMuon", length=10)
    public Date getNgayMuon() {
        return this.ngayMuon;
    }
    
    public void setNgayMuon(Date ngayMuon) {
        this.ngayMuon = ngayMuon;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayTra", length=10)
    public Date getNgayTra() {
        return this.ngayTra;
    }
    
    public void setNgayTra(Date ngayTra) {
        this.ngayTra = ngayTra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HanTra", length=10)
    public Date getHanTra() {
        return this.hanTra;
    }
    
    public void setHanTra(Date hanTra) {
        this.hanTra = hanTra;
    }

    
    @Column(name="GiaHan")
    public Boolean getGiaHan() {
        return this.giaHan;
    }
    
    public void setGiaHan(Boolean giaHan) {
        this.giaHan = giaHan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="thongtinmuontra")
    public Set<Banphat> getBanphats() {
        return this.banphats;
    }
    
    public void setBanphats(Set<Banphat> banphats) {
        this.banphats = banphats;
    }




}


