package entity;
// Generated Dec 10, 2014 9:29:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vitri generated by hbm2java
 */
@Entity
@Table(name="VITRI"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Vitri  implements java.io.Serializable {


     private int id;
     private Integer ke;
     private Integer tang;
     private Integer ngan;
     private Set<Sach> saches = new HashSet<Sach>(0);

    public Vitri() {
    }

	
    public Vitri(int id) {
        this.id = id;
    }
    public Vitri(int id, Integer ke, Integer tang, Integer ngan, Set<Sach> saches) {
       this.id = id;
       this.ke = ke;
       this.tang = tang;
       this.ngan = ngan;
       this.saches = saches;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Ke")
    public Integer getKe() {
        return this.ke;
    }
    
    public void setKe(Integer ke) {
        this.ke = ke;
    }

    
    @Column(name="Tang")
    public Integer getTang() {
        return this.tang;
    }
    
    public void setTang(Integer tang) {
        this.tang = tang;
    }

    
    @Column(name="Ngan")
    public Integer getNgan() {
        return this.ngan;
    }
    
    public void setNgan(Integer ngan) {
        this.ngan = ngan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vitri")
    public Set<Sach> getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set<Sach> saches) {
        this.saches = saches;
    }




}


